# kubernetes/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namasthe-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namasthe-bot
  template:
    metadata:
      labels:
        app: namasthe-bot
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: namasthe-bot
        image: kishanthorat111/namasthe-bot:latest
        envFrom:
          - secretRef:
              name: bot-secrets
        # This new section tells Kubernetes how to create the file
        volumeMounts:
        - name: gcp-credentials-volume
          mountPath: /app/credentials.json
          subPath: credentials.json
      # This new section defines the source of the file
      volumes:
      - name: gcp-credentials-volume
        secret:
          secretName: bot-secrets
          items:
          - key: credentials.json
            path: credentials.json